### ISSUE TITLE
Footer is not aligned to the bottom

### ISSUE THREAD

**Issue by Ryuno-Ki** [Snyk/www#6]
Logged in into [Snyk](https://snyk.io/) (aka being in Dashboard) I noticed that the footer is not aligned to the bottom.
An easy fix would be to add those lines of CSS:
```css
.site-footer {
    position: absolute;
    bottom: 0;
    width: 100%;
}
```
The reason here is too few content on that page.

If it behaves strangely on some devices you may need to add `position: relative` to `.site-footer`'s parent node.
